### PR TITLE
Fix casing in syntax filename

### PR DESCRIPTION
**Pull request by jakergrossman**
Fix casing in syntax filename to correctly apply syntax highlighting when appropriate.

### CODE REVIEW

**Comment by Wafelack** [comment]
It works fine with uppercase word and the plugin's name is capitalized.

**Comment by Wafelack** [comment]
Why should I change if it works with actual capitalized name ?

**Comment by jakergrossman** [comment]
[It does **not** work for me](https://asciinema.org/a/wZQyp0naWwnAk5SItFCHl09y0), unless I set the syntax to `Ark` instead of `ark`.

**Comment by Wafelack** [comment]
Hmm then we can just modify the filetype and the syntax name instead of all the filenames

**Comment by Wafelack** [comment]
Maybe [open an issue](https://github.com/wafelack/ark.vim/issues/) for that problem

**Comment by Wafelack** [comment]
Are changes i made ok to you ?

**Comment by jakergrossman** [comment]
Fixed by b2b3586.

**Pull request closed without merging**
